port: 8081
serverReadTimeout: 1
proxyTimeout: 5

upstreams:
  upstream1:
    condition:
      type: prefix
      value: /api/jokes
    servers:
      - http://127.0.0.1:3000

  upstream2:
    condition:
      type: prefix
      value: /
    servers:
      - 127.0.0.1:3000